- hosts: all
  become: True
  tasks:
    - name: Enable nginx topic from Amazon Linux Extras
      command: amazon-linux-extras install nginx1
      
    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: True

    - name: Deploy static website
      copy:
        src: index.html
        dest: /usr/share/nginx/html/
